package com.example.danil.android.daoGenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.danil.android.daoGenerator.Audio;

import com.example.danil.android.daoGenerator.AudioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig audioDaoConfig;

    private final AudioDao audioDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        audioDao = new AudioDao(audioDaoConfig, this);

        registerDao(Audio.class, audioDao);
    }
    
    public void clear() {
        audioDaoConfig.getIdentityScope().clear();
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

}
